# Generated by Django 2.2.2 on 2019-12-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=9)),
                ('humidity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('lId', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='feild',
            fields=[
                ('location', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('capacity', models.IntegerField()),
                ('fName', models.CharField(max_length=25)),
            ],
        ),
    ]
