# Generated by Django 2.2.2 on 2019-12-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feild',
            old_name='id',
            new_name='lId',
        ),
    ]
