# Generated by Django 2.2.2 on 2019-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20191226_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='feild',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feild',
            name='lId',
            field=models.IntegerField(unique=True),
        ),
    ]
